.TH "dbo/action/ActionOption.cpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/action/ActionOption.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'dbo/action/ActionOption\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBActionOption\fP \fBoperator|\fP (\fBActionOption\fP lhs, \fBActionOption\fP rhs)"
.br
.RI "\fICombines two options\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBActionOption\fP operator| (\fBActionOption\fPlhs, \fBActionOption\fPrhs)"

.PP
Combines two options\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
