.TH "dbo/collection.hpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/collection.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <deque>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbo::ptr< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::collection< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::collection< C >::iterator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
