.TH "dbo::traits::sql_value_traits< std::vector< unsigned char >, void >" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::traits::sql_value_traits< std::vector< unsigned char >, void > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StdSqlTraits\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBtype\fP (int size)"
.br
.ti -1c
.RI "static void \fBbind\fP (const std::vector< unsigned char > &v, \fBstmt::Statement\fP &statement, int size)"
.br
.ti -1c
.RI "static bool \fBread\fP (std::vector< unsigned char > &v, \fBstmt::Statement\fP &statement, int size)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBspecialized\fP =true"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void \fBdbo::traits::sql_value_traits\fP< std::vector< unsigned char >, void >::bind (const std::vector< unsigned char > &v, \fBstmt::Statement\fP &statement, intsize)\fC [static]\fP"

.SS "static bool \fBdbo::traits::sql_value_traits\fP< std::vector< unsigned char >, void >::read (std::vector< unsigned char > &v, \fBstmt::Statement\fP &statement, intsize)\fC [static]\fP"

.SS "static std::string \fBdbo::traits::sql_value_traits\fP< std::vector< unsigned char >, void >::type (intsize)\fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const bool \fBdbo::traits::sql_value_traits\fP< std::vector< unsigned char >, void >::specialized =true\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
