.TH "dbo::stmt::BulkStatement::Buffer" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::stmt::BulkStatement::Buffer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BulkStatement\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuffer\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBdata_\fP [\fBBuffSize\fP]"
.br
.ti -1c
.RI "size_t \fBsize_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dbo::stmt::BulkStatement::Buffer::Buffer ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned char dbo::stmt::BulkStatement::Buffer::data_[\fBBuffSize\fP]"

.SS "size_t dbo::stmt::BulkStatement::Buffer::size_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
