.TH "dbo::connection::typecomp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::connection::typecomp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <connection\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const \fBconst_typeinfo_ptr\fP &lhs, const \fBconst_typeinfo_ptr\fP &rhs) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool dbo::connection::typecomp::operator() (const \fBconst_typeinfo_ptr\fP &lhs, const \fBconst_typeinfo_ptr\fP &rhs) const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
