.TH "dbo::ActionOption" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::ActionOption \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ActionOption\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActionOption\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBActionOption\fP &other)"
.br
.ti -1c
.RI "int \fBvalue\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ActionOption::ActionOption (intvalue)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ActionOption::operator== (const \fBActionOption\fP &other)"

.SS "int dbo::ActionOption::value () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
