.TH "dbo/traits/dbo_default_traits.hpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/traits/dbo_default_traits.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/optional\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbo_default_traits\fP"
.br
.RI "\fIDefault traits for a class mapped with %Dbo\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
