.TH "dbo::action::LoadDb< C >" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::action::LoadDb< C > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LoadDb\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBIdType\fP = typename \fBtraits::dbo_traits\fP< C >::\fBIdType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoadDb\fP (\fBptr\fP< C > &\fBptr\fP, std::shared_ptr< \fBmapping::Mapping\fP< C >> mapping, \fBstmt::PreparedStatement\fP &stmt)"
.br
.ti -1c
.RI "void \fBvisit\fP ()"
.br
.ti -1c
.RI "template<typename V > void \fBact\fP (const \fBmapping::FieldRef\fP< V > &\fBfield\fP)"
.br
.ti -1c
.RI "template<typename V > void \fBactId\fP (V &value, const std::string &name, int size)"
.br
.ti -1c
.RI "template<class D > void \fBactId\fP (\fBptr\fP< D > &value, const std::string &name, int size, int fkConstraints)"
.br
.ti -1c
.RI "template<class D > void \fBactPtr\fP (const \fBmapping::PtrRef\fP< D > &\fBfield\fP)"
.br
.ti -1c
.RI "\fBconnection\fP & \fBconn\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<class D > class \fBLoadDb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class C>class dbo::action::LoadDb< C >"
Load an object from statement current state 
.SH "Member Typedef Documentation"
.PP 
.SS "template<class C > using \fBdbo::action::LoadDb\fP< C >::\fBIdType\fP =  typename \fBtraits::dbo_traits\fP<C>::\fBIdType\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class C > \fBdbo::action::LoadDb\fP< C >::\fBLoadDb\fP (\fBptr\fP< C > &ptr, std::shared_ptr< \fBmapping::Mapping\fP< C >>mapping, \fBstmt::PreparedStatement\fP &stmt)"

.SH "Member Function Documentation"
.PP 
.SS "template<class C > template<typename V > void \fBdbo::action::LoadDb\fP< C >::act (const \fBmapping::FieldRef\fP< V > &field)"

.SS "template<class C > template<typename V > void \fBdbo::action::LoadDb\fP< C >::actId (V &value, const std::string &name, intsize)"

.SS "template<class C > template<class D > void \fBdbo::action::LoadDb\fP< C >::actId (\fBptr\fP< D > &value, const std::string &name, intsize, intfkConstraints)"

.SS "template<class C > template<class D > void \fBdbo::action::LoadDb\fP< C >::actPtr (const \fBmapping::PtrRef\fP< D > &field)"

.SS "template<class C > \fBconnection\fP& \fBdbo::action::LoadDb\fP< C >::conn ()\fC [inline]\fP"

.SS "template<class C > void \fBdbo::action::LoadDb\fP< C >::visit ()"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class C > template<class D > friend class \fBLoadDb\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
