.TH "dbo::traits::sql_value_traits< boost::optional< T >, void >" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::traits::sql_value_traits< boost::optional< T >, void > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StdSqlTraits\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBtype\fP (int size)"
.br
.ti -1c
.RI "static void \fBbind\fP (const boost::optional< T > &v, \fBstmt::Statement\fP &statement, int size)"
.br
.ti -1c
.RI "static bool \fBread\fP (boost::optional< T > &v, \fBstmt::Statement\fP &statement, int size)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBspecialized\fP =true"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T > static void \fBdbo::traits::sql_value_traits\fP< boost::optional< T >, void >::bind (const boost::optional< T > &v, \fBstmt::Statement\fP &statement, intsize)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static bool \fBdbo::traits::sql_value_traits\fP< boost::optional< T >, void >::read (boost::optional< T > &v, \fBstmt::Statement\fP &statement, intsize)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T > static std::string \fBdbo::traits::sql_value_traits\fP< boost::optional< T >, void >::type (intsize)\fC [inline]\fP, \fC [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename T > const bool \fBdbo::traits::sql_value_traits\fP< boost::optional< T >, void >::specialized =true\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
