.TH "dbo::ptr< C >::Ptr" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::ptr< C >::Ptr \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ptr\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "C * \fBvalue_\fP"
.br
.ti -1c
.RI "size_t \fBref_\fP"
.br
.ti -1c
.RI "\fBIdType\fP \fBid_\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "template<class C> \fBIdType\fP \fBdbo::ptr\fP< C >::Ptr::id_"

.SS "template<class C> size_t \fBdbo::ptr\fP< C >::Ptr::ref_"

.SS "template<class C> C* \fBdbo::ptr\fP< C >::Ptr::value_"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
