.TH "dbo::opt" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::opt \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "const \fBActionOption\fP \fBNone\fP (\fBOptNone\fP)"
.br
.ti -1c
.RI "const \fBActionOption\fP \fBRecursive\fP (\fBOptRecursive\fP)"
.br
.ti -1c
.RI "const \fBActionOption\fP \fBReload\fP (\fBOptReload\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "const \fBActionOption\fP dbo::opt::None (OptNone)"

.SS "const \fBActionOption\fP dbo::opt::Recursive (OptRecursive)"

.SS "const \fBActionOption\fP dbo::opt::Reload (OptReload)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
