.TH "dbo::mapping::Mapping< T >" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::mapping::Mapping< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BulkInsert\&.hpp>\fP
.PP
Inherits \fBdbo::mapping::MappingInfo\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMapping\fP ()"
.br
.ti -1c
.RI "virtual \fB~Mapping\fP ()"
.br
.ti -1c
.RI "virtual void \fBinit\fP (\fBconnection\fP &conn)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class C > \fBdbo::mapping::Mapping\fP< C >::\fBMapping\fP ()"

.SS "template<class C > \fBdbo::mapping::Mapping\fP< C >::~\fBMapping\fP ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class C > void \fBdbo::mapping::Mapping\fP< C >::init (\fBconnection\fP &conn)\fC [virtual]\fP"

.PP
Reimplemented from \fBdbo::mapping::MappingInfo\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
