.TH "dbo::mapping::JoinId" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::mapping::JoinId \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <JoinId\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJoinId\fP (const std::string &aJoinIdName, const std::string &aTableIdName, const std::string &aSqlType)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBjoinIdName\fP"
.br
.ti -1c
.RI "std::string \fBtableIdName\fP"
.br
.ti -1c
.RI "std::string \fBsqlType\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "dbo::mapping::JoinId::JoinId (const std::string &aJoinIdName, const std::string &aTableIdName, const std::string &aSqlType)"

.SH "Member Data Documentation"
.PP 
.SS "std::string dbo::mapping::JoinId::joinIdName"

.SS "std::string dbo::mapping::JoinId::sqlType"

.SS "std::string dbo::mapping::JoinId::tableIdName"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
