.TH "dbo::mapping::FieldRef< T >" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::mapping::FieldRef< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BulkInsert\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldRef\fP (V &\fBvalue\fP, const std::string &\fBname\fP, int \fBsize\fP)"
.br
.ti -1c
.RI "const std::string & \fBname\fP () const "
.br
.ti -1c
.RI "int \fBsize\fP () const "
.br
.ti -1c
.RI "std::string \fBsqlType\fP () const "
.br
.ti -1c
.RI "const std::type_info * \fBtype\fP () const "
.br
.ti -1c
.RI "V & \fBvalue\fP () const "
.br
.ti -1c
.RI "void \fBsetValue\fP (const V &\fBvalue\fP) const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename V > \fBdbo::mapping::FieldRef\fP< V >::\fBFieldRef\fP (V &value, const std::string &name, intsize)"

.SH "Member Function Documentation"
.PP 
.SS "template<typename V > const std::string & \fBdbo::mapping::FieldRef\fP< V >::name () const"

.SS "template<class T> void \fBdbo::mapping::FieldRef\fP< T >::setValue (const V &value) const\fC [inline]\fP"

.SS "template<typename V > int \fBdbo::mapping::FieldRef\fP< V >::size () const"

.SS "template<typename V > std::string \fBdbo::mapping::FieldRef\fP< V >::sqlType () const"

.SS "template<typename V > const std::type_info * \fBdbo::mapping::FieldRef\fP< V >::type () const"

.SS "template<class T> V& \fBdbo::mapping::FieldRef\fP< T >::value () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
