.TH "dbo::ForeignKeyConstraint" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::ForeignKeyConstraint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ForeignKeyConstraint\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForeignKeyConstraint\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "int \fBvalue\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ForeignKeyConstraint::ForeignKeyConstraint (intvalue)\fC [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int dbo::ForeignKeyConstraint::value () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
