.TH "dbo::mapping::CollectionRef< T >" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::mapping::CollectionRef< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <InitSchema\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectionRef\fP (\fBcollection\fP< C > &\fBvalue\fP, \fBRelationType\fP \fBtype\fP, const std::string &\fBjoinName\fP, const std::string &\fBjoinId\fP, int \fBfkConstraints\fP)"
.br
.ti -1c
.RI "\fBcollection\fP< C > & \fBvalue\fP () const "
.br
.ti -1c
.RI "const std::string & \fBjoinName\fP () const "
.br
.ti -1c
.RI "const std::string & \fBjoinId\fP () const "
.br
.ti -1c
.RI "\fBRelationType\fP \fBtype\fP () const "
.br
.ti -1c
.RI "int \fBfkConstraints\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBdbo::mapping::CollectionRef\fP< T >::\fBCollectionRef\fP (\fBcollection\fP< C > &value, \fBRelationType\fPtype, const std::string &joinName, const std::string &joinId, intfkConstraints)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class T> int \fBdbo::mapping::CollectionRef\fP< T >::fkConstraints () const\fC [inline]\fP"

.SS "template<class T> const std::string& \fBdbo::mapping::CollectionRef\fP< T >::joinId () const\fC [inline]\fP"

.SS "template<class T> const std::string& \fBdbo::mapping::CollectionRef\fP< T >::joinName () const\fC [inline]\fP"

.SS "template<class T> \fBRelationType\fP \fBdbo::mapping::CollectionRef\fP< T >::type () const\fC [inline]\fP"

.SS "template<class T> \fBcollection\fP<C>& \fBdbo::mapping::CollectionRef\fP< T >::value () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
