.TH "dbo::mapping" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::mapping \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCollectionRef\fP"
.br
.ti -1c
.RI "class \fBFieldInfo\fP"
.br
.RI "\fIDescription of a field\&. \fP"
.ti -1c
.RI "class \fBFieldRef\fP"
.br
.ti -1c
.RI "struct \fBJoinId\fP"
.br
.ti -1c
.RI "class \fBMapping\fP"
.br
.ti -1c
.RI "class \fBMappingInfo\fP"
.br
.ti -1c
.RI "class \fBPtrRef\fP"
.br
.ti -1c
.RI "struct \fBSetInfo\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBFKNotNull\fP = 0x01"
.br
.ti -1c
.RI "const int \fBFKOnUpdateCascade\fP = 0x02"
.br
.ti -1c
.RI "const int \fBFKOnUpdateSetNull\fP = 0x04"
.br
.ti -1c
.RI "const int \fBFKOnDeleteCascade\fP = 0x08"
.br
.ti -1c
.RI "const int \fBFKOnDeleteSetNull\fP = 0x10"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int dbo::mapping::FKNotNull = 0x01"

.SS "const int dbo::mapping::FKOnDeleteCascade = 0x08"

.SS "const int dbo::mapping::FKOnDeleteSetNull = 0x10"

.SS "const int dbo::mapping::FKOnUpdateCascade = 0x02"

.SS "const int dbo::mapping::FKOnUpdateSetNull = 0x04"

.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
