.TH "dbo::traits::sql_value_traits< Enum, typename boost::enable_if< boost::is_enum< Enum > >::type >" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo::traits::sql_value_traits< Enum, typename boost::enable_if< boost::is_enum< Enum > >::type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StdSqlTraits\&.h>\fP
.PP
Inherits \fBdbo::traits::sql_value_traits< int >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBbind\fP (Enum v, \fBstmt::Statement\fP &statement, int size)"
.br
.ti -1c
.RI "static bool \fBread\fP (Enum &v, \fBstmt::Statement\fP &statement, int size)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "template<typename Enum > static void \fBdbo::traits::sql_value_traits\fP< Enum, typename boost::enable_if< boost::is_enum< Enum > >::type >::bind (Enumv, \fBstmt::Statement\fP &statement, intsize)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename Enum > static bool \fBdbo::traits::sql_value_traits\fP< Enum, typename boost::enable_if< boost::is_enum< Enum > >::type >::read (Enum &v, \fBstmt::Statement\fP &statement, intsize)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
