.TH "dbo/traits/dbo_traits.hpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/traits/dbo_traits.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dbo/traits/dbo_default_traits\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbo::traits::dbo_traits< C >\fP"
.br
.RI "\fITraits for a class mapped with %Dbo\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::traits\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
