.TH "dbo/mapping/Field.h" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/mapping/Field.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::mapping\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBdbo::mapping::FKNotNull\fP = 0x01"
.br
.ti -1c
.RI "const int \fBdbo::mapping::FKOnUpdateCascade\fP = 0x02"
.br
.ti -1c
.RI "const int \fBdbo::mapping::FKOnUpdateSetNull\fP = 0x04"
.br
.ti -1c
.RI "const int \fBdbo::mapping::FKOnDeleteCascade\fP = 0x08"
.br
.ti -1c
.RI "const int \fBdbo::mapping::FKOnDeleteSetNull\fP = 0x10"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
