.TH "dbo/mapping/FieldInfo.h" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/mapping/FieldInfo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbo::mapping::FieldInfo\fP"
.br
.RI "\fIDescription of a field\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::mapping\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
