.TH "dbo/action/InitSchema.hpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/action/InitSchema.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <dbo/mapping/SetInfo\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbo::mapping::CollectionRef< T >\fP"
.br
.ti -1c
.RI "class \fBdbo::mapping::FieldRef< T >\fP"
.br
.ti -1c
.RI "class \fBdbo::mapping::PtrRef< T >\fP"
.br
.ti -1c
.RI "class \fBdbo::action::InitSchema\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::mapping\fP"
.br
.ti -1c
.RI " \fBdbo::action\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
