.TH "dbo/ptr.cxx" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/ptr.cxx \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class C > std::ostream & \fBdbo::operator<<\fP (std::ostream &o, const \fBdbo::ptr\fP< C > &_ptr)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
