.TH "dbo/ptr.hpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/ptr.hpp \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbo::action::Delete< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::action::Insert< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::action::Update< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::action::SelectById< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::collection< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::ptr< C >\fP"
.br
.ti -1c
.RI "class \fBdbo::ptr_base\fP"
.br
.ti -1c
.RI "class \fBdbo::ptr< C >\fP"
.br
.ti -1c
.RI "struct \fBdbo::ptr< C >::Ptr\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::action\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class C > std::ostream & \fBdbo::operator<<\fP (std::ostream &o, const \fBdbo::ptr\fP< C > &_ptr)"
.br
.ti -1c
.RI "template<typename _Tp , typename\&.\&.\&. _Args> ptr< _Tp > \fBdbo::make_ptr\fP (_Args &&\&.\&.\&.__args)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
