.TH "dbo/mapping/PtrRef.hpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/mapping/PtrRef.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dbo/ptr\&.hpp>\fP
.br
\fC#include <dbo/traits/dbo_traits\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdbo::mapping::PtrRef< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::mapping\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
