.TH "dbo/mapping/SetInfo.h" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/mapping/SetInfo.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBdbo::mapping::SetInfo\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::mapping\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBdbo::RelationType\fP { \fBdbo::ManyToOne\fP, \fBdbo::ManyToMany\fP }"
.br
.RI "\fIType of an SQL relation\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
