.TH "dbo/traits/StdSqlTraits.h" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/traits/StdSqlTraits.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <boost/optional\&.hpp>\fP
.br
\fC#include <boost/date_time/posix_time/posix_time\&.hpp>\fP
.br
\fC#include <boost/utility/enable_if\&.hpp>\fP
.br
\fC#include <boost/type_traits/is_enum\&.hpp>\fP
.br
\fC#include <dbo/traits/sql_value_traits\&.hpp>\fP
.br
\fC#include <dbo/stmt/Statement\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBis_raw_string< Type >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< std::string, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< Type, typename boost::enable_if< is_raw_string< Type > >::type >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< long long, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< int, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< long, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< short, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< bool, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< float, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< double, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< size_t, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< boost::gregorian::date, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< boost::posix_time::ptime, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< boost::posix_time::time_duration, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< Enum, typename boost::enable_if< boost::is_enum< Enum > >::type >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< std::vector< unsigned char >, void >\fP"
.br
.ti -1c
.RI "struct \fBdbo::traits::sql_value_traits< boost::optional< T >, void >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdbo\fP"
.br
.ti -1c
.RI " \fBdbo::stmt\fP"
.br
.ti -1c
.RI " \fBdbo::traits\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
