.TH "dbo/transaction.cpp" 3 "Sat Feb 27 2016" "Dbo" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbo/transaction.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <dbo/transaction\&.h>\fP
.br
\fC#include <dbo/connection\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Dbo from the source code\&.
